# Generated by Django 4.0.6 on 2022-10-06 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_courses_courseimg_alter_track_trackimg'),
        ('accounts', '0002_userprofile_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.courses'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.track'),
        ),
    ]
