# Generated by Django 4.0.6 on 2022-10-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('begin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startcourse',
            name='imgSource1',
            field=models.ImageField(upload_to='photo'),
        ),
        migrations.AlterField(
            model_name='startcourse',
            name='imgSource2',
            field=models.ImageField(upload_to='photo'),
        ),
        migrations.AlterField(
            model_name='startcourse',
            name='imgSource3',
            field=models.ImageField(upload_to='photo'),
        ),
        migrations.AlterField(
            model_name='startcourse',
            name='imgSource4',
            field=models.ImageField(upload_to='photo'),
        ),
    ]
