# Generated by Django 4.0.6 on 2022-10-08 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_coursescontent_trackcontent_courses_coursecontent_and_more'),
        ('begin', '0002_alter_startcourse_imgsource1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackAdvice', models.TextField()),
                ('youtubeSource1', models.CharField(max_length=200)),
                ('imgSource1', models.ImageField(upload_to='photo')),
                ('desSource1', models.CharField(max_length=200)),
                ('youtubeSource2', models.CharField(max_length=200)),
                ('imgSource2', models.ImageField(upload_to='photo')),
                ('desSource2', models.CharField(max_length=200)),
                ('documentSource1', models.CharField(max_length=200)),
                ('imgSource3', models.ImageField(upload_to='photo')),
                ('desSource3', models.CharField(max_length=200)),
                ('documentSource2', models.CharField(max_length=200)),
                ('imgSource4', models.ImageField(upload_to='photo')),
                ('desSource4', models.CharField(max_length=200)),
                ('starttrack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.trackcontent')),
            ],
        ),
    ]
