# Generated by Django 4.0.6 on 2022-10-08 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_coursescontent_trackcontent_courses_coursecontent_and_more'),
        ('begin', '0003_starttrack'),
    ]

    operations = [
        migrations.CreateModel(
            name='trackCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finishedDate', models.DateTimeField()),
                ('finishedTrack', models.ManyToManyField(to='home.trackcontent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finishedDate', models.DateTimeField()),
                ('finishedCourse', models.ManyToManyField(to='home.coursescontent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
