# Generated by Django 4.0.6 on 2022-10-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseName', models.CharField(max_length=40)),
                ('courseImg', models.ImageField(upload_to='courses')),
                ('courseDescription', models.TextField(max_length=200)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TrackName', models.CharField(max_length=40)),
                ('TrackImg', models.ImageField(upload_to='track')),
                ('TrackDescription', models.TextField(max_length=200)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
