# Generated by Django 4.0.6 on 2022-10-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_courses_courseimg_alter_track_trackimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CName', models.CharField(max_length=40, verbose_name='Course Name')),
                ('cImg', models.ImageField(upload_to='photo', verbose_name='Course Image')),
                ('cDescription', models.TextField(max_length=200, verbose_name='Course Description')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TrackContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TName', models.CharField(max_length=40, verbose_name='Track Name')),
                ('Tmg', models.ImageField(upload_to='photo', verbose_name='Track Image')),
                ('TDescription', models.TextField(max_length=200, verbose_name='Track Description')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='courses',
            name='courseContent',
            field=models.ManyToManyField(to='home.coursescontent'),
        ),
        migrations.AddField(
            model_name='track',
            name='TrackContent',
            field=models.ManyToManyField(to='home.trackcontent'),
        ),
    ]
